import Head from 'next/head'

export default function DetalhesPage() {
  return (
    <div>
      <Head>
        <title>detalhes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>detalhes</h1>
    </div>
  )
}
