import Head from 'next/head'
import { useRouter } from 'next/router'

import * as S from './styles'

export default function DetalhesMoviePage() {
  const router = useRouter()
  const { id } = router.query

  return (
    <div>
      <Head>
        <title>detalhes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.Title>infos do filme {id}</S.Title>
    </div>
  )
}
